### ISSUE TITLE
Rewrite this crap in Go

### ISSUE THREAD

**Issue by meatballhat** [meatballhat/git-duet#17]
- [x] I've had it with you, Ruby
- [x] `(╯°□°)╯︵ ┻━┻`
- [x] no really

**Comment by tomwhoiscontrary** [comment]
Would you still accept a PR on this project (and make a release for it), or is it all Go, all the time these days?

**Comment by meatballhat** [comment]
@tomwhoiscontrary PRs accepted!  Since the collapse of ModCloth Engineering, zero effort has gone into the Go rewrite, and my current workplace doesn't do much in the way of pairing.  Have at it!

**Comment by tomwhoiscontrary** [comment]
I'm sorry to hear that. We use git-duet pretty much non-stop at Pivotal Labs, if it's any consolation. I'll open another issue to run the idea by you ...

**Comment by rafecolton** [comment]
We haven't touched the Go version in nearly a year.  Maybe it's time to close this issue?  Ruby's not so bad

**Comment by jszwedko** [comment]
I personally still dream of a cross-compiled binary future just because of the idiosyncrasies of installing a gem that is a "tool" when using `rvm` or `rbenv` which usually end in frustration. But I think it's cool to add features to the Ruby version until such time.

**Comment by jszwedko** [comment]
Working on this at https://github.com/jszwedko/go-git-duet

**Comment by jszwedko** [comment]
Completed https://github.com/git-duet/git-duet
