### ISSUE TITLE
Provide some way of making global pairing the default

### ISSUE THREAD

**Issue by tomwhoiscontrary** [meatballhat/git-duet#27]
It's useful to have the choice between setting a pair for a particular repo, and setting it globally. But in my experience, you have to consistently do one or the other - they don't mix well. I keep getting into situations where i'm committing as someone who worked on the machine the previous day, but set their pair differently. I could fix this by having a more effective brain, but realistically, that's not going to happen.

So, what i'd like to do is have some way of forcing global pairing on a machine. So if someone writes `git pair kb wc`, it actually sets a global pair. That way, there's only global pairing, and no confusion.

Forcing global pairing, rather than local pairing, makes more sense for us, as we often have multi-repo projects, with a pair at one machine committing to multiple repositories in the same session.

If you think this is a sane feature, and if i can find some way of implementing it sanely, i am happy to submit a PR.

The best thing i've thought of so far is an environment variable. It could be GIT_DUET_GLOBAL, which forces globalness if set. Or it could be GIT_DUET_OPTS, which is added to the command line, so it could contain other options (if there are ever any). How does that sound?

**Comment by rafecolton** [comment]
I'd rather have the option be configurable through the environment than be dependent on the format of the command line arguments.  No objections to the feature - sounds like a useful addition!

**Comment by jszwedko** [comment]
I'm :+1: to the environment.

**Comment by codeword** [comment]
can you cut a new gem with this feature and release to RubyGems

**Comment by jszwedko** [comment]
@codeword released as version `0.5.1`, thanks for the poke!

**Comment by tomwhoiscontrary** [comment]
:+1: thanks to @codeword and @jszwedko. I realise i should have carried on and encouraged a release, but am too lazy. Anyway, :shipit:.

@codeword is this worth a mail to labs-developers?

**Comment by meatballhat** [comment]
:heart_eyes_cat:
